### ISSUE TITLE
Define next steps

### ISSUE THREAD

**Issue by cmungall** [GenomicsStandardsConsortium/mixs-ng#1]
Myself and @wdduncan can help out here but it would be good to have an idea of the plan moving forward, and some more documentation of the 3 different schema files and their intended purposes.

(Sorry for the vague ticket, I will update later, wanted to file before forgetting)

**Comment by ramonawalls** [comment]
I am about to file some initial tickets for first steps, and we can also flesh this out at our first call on Dec. 9 (pending).

**Comment by ramonawalls** [comment]
We now have other tickets and a new repo. @cmungall can you please close this issue?
