### ISSUE TITLE
Decide on format for MIxS PURLs

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs-ng#3]
Although JSON does not strictly require term urls, much of what people need to do with mixs does (e.g., use mixs in linked data, use mixs terms in ontologies).

We discusses this topic at the CIG hackathon in Vienna in May.
Options include:
- Use obo foundry purls
- Make gensc purls
- Make gensc URLs that are not purls (e.g., gensc.org/ns)
- Keep namespace for terms in TDWG

**Comment by cmungall** [comment]
Also https://w3id.org/

**Comment by lschriml** [comment]
The last time we discussed this at the board level, there was a lot of support for: 
Make gensc purls
   --> Has this been discussed further on the CIG calls ? 

Cheers,
Lynn
