### ISSUE TITLE
Explore existing code we could reuse

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs-ng#5]
There is a lot of code out there on creating JSON metadata. Some of it may be useful.

Please add links to resources as comments on this issue.

**Comment by ramonawalls** [comment]
https://github.com/tdwg/dwc
https://github.com/earthcubearchitecture-project418/gleaner

**Comment by ramonawalls** [comment]
Could we use some of the GEOME code for validation? https://github.com/biocodellc/geome-db

**Comment by jjkoehorst** [comment]
Maybe http://empusa.org could be of use (I am co-developer), it does listen to a mix of OWL/SheX and can be used for API generation according to schema / property information

**Comment by ramonawalls** [comment]
Consider wikibase

**Comment by cmungall** [comment]
CEDAR is another one. I broke this into its own ticket: #6

**Comment by lschriml** [comment]
As we are contemplating code, please also include their licensing information in the discussion.

Cheers,
Lynn

**Comment by ramonawalls** [comment]
If this discussion needs to be continue, please file issues at https://github.com/GenomicsStandardsConsortium/mixs-rdf/issues
