### ISSUE TITLE
Fix overspecification of parameter definitions

### ISSUE THREAD

**Issue by pbuttigieg** [GenomicsStandardsConsortium/mixs-ng#8]
CC @jzrapp

For example, "porosity" applies to more than just soil (sediment, sea ice). We should relabel or remove overspecified parameters on detection.

**Comment by ramonawalls** [comment]
Changes to existing MIxS terms and new term requests are still being handled in the original MIxS repo. I will copy this issue there, then please close this one, @pbuttigieg
