### ISSUE TITLE
Create "support" package modules

### ISSUE THREAD

**Issue by pbuttigieg** [GenomicsStandardsConsortium/mixs-ng#9]
CC @jzrapp (perhaps link to the Cryo spreadsheet you've developed?)

For parameter groups that are repeated across multiple environmental packages (e.g. sample logistics)

These support packages (or parts of them) would be sourced by the environmental packages that need them, perhaps driven by an import file that would pull in either single parameters or the whole package.

**Comment by ramonawalls** [comment]
@pbuttigieg I have copied this issue to GenomicsStandardsConsortium/mixs-rdf#4. Can you please close this issue?
